export const defaultTheme = {
  colors: {
    background: '#FAFAFA',
    'base-button': '#E6E5E5',
    'base-card': '#F3F2F2',
    'base-subtitle': '#403937',
    'base-title': '#272221',
    'base-text': '#574F4D',
    'base-label': '#8D8686',
    'base-hover': '#D7D5D5',
    'base-input': '#EDEDED',
    'yellow-dark': '#C47F17',
    yellow: '#DBAC2C',
    'yellow-light': '#F1E9C9',
    'purple-dark': '#4B2995',
    purple: '#8047F8',
    'purple-light': '#EBE5F9',
    white: '#FFFFFF',
  },
  fonts: {
    baloo: 'Baloo 2, cursive',
    roboto: 'Roboto, sans-serif',
  },
  pixelToRem: (size: number) => `${size / 16}rem`,
}
